[package]
name = "commonwl"
description = "Rust implementation of the CommonWorkflowLanguage (CWL) standard"
readme = "README.md"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
cwl_core = { version = "0", path = "../core" }
cwl_engine = { version = "0", path = "../engine", optional = true }
cwl_engine_storage = { version = "0", path = "../storage", optional = true }

[features]
default = []
engine = ["dep:cwl_engine", "dep:cwl_engine_storage"]
tes = ["engine", "cwl_engine/tes"]

[lib]
path = "lib.rs"
