[package]
name = "commonwl"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
cwl_core = { version = "*", path = "../core" }
cwl_engine = { version = "*", path = "../engine", optional = true }

[features]
default = []
engine = ["cwl_engine"]

[lib]
path = "lib.rs"
