[workspace]
members = [
    "crates/commonwl",
    "crates/conformance",
    "crates/core",
    "crates/engine",
    "crates/lsp",
    "crates/salad",
    "crates/salad_derive",
    "crates/storage",
]

resolver = "3"

[workspace.package]
version = "0.14.0"
edition = "2024"
rust-version = "1.95"
repository = "https://github.com/fairagro/commonwl"
license = "MIT OR Apache-2.0"
keywords = ["cwl", "commonwl", "workflow", "fairagro"]
authors = [
    "Jens Krumsieck",
    "Antonia Leidel",
    "Harald von Waldow",
    "Xaver Stiensmeier",
    "FAIRagro",
]
categories = ["science"]

[workspace.dependencies]
# internal
commonwl = { version = "0", path = "crates/commonwl" }
cwl_core = { version = "0", path = "crates/core" }
cwl_engine = { version = "0", path = "crates/engine" }
cwl_engine_storage = { version = "0", path = "crates/storage" }
cwl_salad = { version = "0", path = "crates/salad" }
cwl_salad_derive = { version = "0", path = "crates/salad_derive" }

# serde
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde-saphyr = { version = "1.1.0", features = ["miette", "validator"] }

# async
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"
async-trait = "0.1.91"
futures-util = "0.3.34"
crankshaft = { version = "0.10.0", features = ["docker"] }
boa_engine = "0.21.1"
bollard = "^0.19"

# error handling
anyhow = "1.0.104"
thiserror = "2.0.20"
miette = "7.6.0"
validator = { version = "0.21.0", features = ["derive"] }

# I/O
dircpy = "0.3.20"
dunce = "1.0.5"
tempfile = "3.27.0"
same-file = "1.0.6"
pathdiff = "0.2.3"
tar = "0.4.46"
glob = "0.3.4"
base16ct = "1.0.0"
sha1 = "0.11.0"


# network
url = "2.5.8"
reqwest = "0.13.4"
aws-sdk-s3 = "1.139.0"
aws-config = { version = "1.10.1", features = ["behavior-version-latest"] }
dotenvy = "0.15.7"

# log
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

# rdf
rdf = "0.1.4"
horned-owl = "3.0.0"

# lsp
tower-lsp-server = "0.23.0"
dashmap = "6.2.1"
ropey = "1.6.1"
granit-parser = "1.0.1"

# util
chrono = { version = "0.4.45" }
uuid = { version = "1.24.0", features = ["v4"] }
regex = "1.12.3"
semver = "1.0.28"
urlencoding = "2.1.3"
indexmap = "2.14.0"
nonempty = "0.12.0"
oneormany = { version = "1.0.0", features = ["serde"] }
sysinfo = "0.39.2"
nix = { version = "0.31.3", features = ["user"] }
bon = "3.9.3"
syn = "3.0.4"
quote = "1.0.45"
proc-macro2 = "1.0.106"
clap = "4.6.4"

# test
trybuild = "1.0.116"
