[package]
name = "cwl_engine_storage"
description = "Part of `CommonWL`. Storage impl"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true


[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
glob = "0.3.3"
tokio.workspace = true
url.workspace = true
aws-sdk-s3 = "1.125.0"
aws-config = { version = "1.8.15", features = ["behavior-version-latest"] }
reqwest.workspace = true
dotenvy = "0.15.7"
dircpy.workspace = true
tempfile.workspace = true
uuid.workspace = true
tracing.workspace = true
