[package]
name = "cwl_engine_storage"
description = "Part of `CommonWL`. Storage impl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
dunce.workspace = true
glob.workspace = true
tokio.workspace = true
url.workspace = true
aws-sdk-s3.workspace = true
aws-config.workspace = true
reqwest.workspace = true
dotenvy.workspace = true
dircpy.workspace = true
tempfile.workspace = true
uuid.workspace = true
tracing.workspace = true
