[package]
name = "conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
commonwl = { workspace = true, features = ["engine", "tes"] }
cwl_engine_storage.workspace = true
crankshaft.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde_json.workspace = true
tokio-util.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
