[package]
name = "cwl-lsp"
description = "CWL Language Server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
cwl_core.workspace = true
tower-lsp-server.workspace = true
dashmap.workspace = true
ropey.workspace = true
tracing-subscriber.workspace = true
granit-parser.workspace = true
