[package]
name = "cwl-lsp"
description = "CWL Language Server"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
cwl_core.workspace = true
tower-lsp-server = "0.23.0"
dashmap = "6.2.1"
ropey = "1.6.1"
tracing-subscriber.workspace = true
granit-parser = "0.0.3"
