[package]
name = "cwl_execution"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
serde_yaml.workspace = true
anyhow = "1.0.100"
crankshaft = { version = "0.7.0", features = ["docker"] }
cwl_core.workspace = true
nonempty = "0.12.0"
tempfile = "3.24.0"
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = "0.7.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
url = "2.5.8"
shlex = "1.3.0"
bollard = "^0.19.2"
futures-util = "0.3.31"
tar = "0.4.44"
