[package]
name = "commonwl_salad"
description = "schema salad types"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
commonwl_salad_derive = { version = "0", path = "../salad_derive", optional = true }
serde.workspace = true
serde_yaml.workspace = true

[lib]
path = "lib.rs"

[features]
default = []
derive = ["commonwl_salad_derive"]
