[package]
name = "cwl_salad"
description = "schema salad types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lib]
path = "lib.rs"

[features]
default = []
derive = ["cwl_salad_derive"]

[dependencies]
cwl_salad_derive = { workspace = true, optional = true }
serde.workspace = true
serde-saphyr.workspace = true
serde_json.workspace = true

[dev-dependencies]
trybuild.workspace = true

[[test]]
name = "derive_identifiable"
required-features = ["derive"]