[package]
name = "commonwl_salad"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
commonwl_salad_derive = { version = "*", path = "../salad_derive", optional = true }

[lib]
path = "lib.rs"

[features]
default = []
derive = ["commonwl_salad_derive"]
