[package]
name = "cwl_salad_derive"
description = "Derive Macro for commonwl_salad"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true