[package]
name = "cwl_salad_derive"
description = "Derive Macro for commonwl_salad"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = "2.0.117"
quote = "1.0.44"
proc-macro2 = "1.0.106"