[package]
name = "cwl_engine"
description = "Part of `CommonWL`. CWL Execution"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[lib]
path = "lib.rs"

[package.metadata.docs.rs]
all-features = true

[features]
tes = []

[dependencies]
# serialization
serde.workspace = true
serde-saphyr.workspace = true
serde_json.workspace = true
cwl_core.workspace = true

# runtime
crankshaft.workspace = true
boa_engine.workspace = true
bollard.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures-util.workspace = true

# io
dunce.workspace = true
sha1.workspace = true
base16ct.workspace = true
pathdiff.workspace = true
tempfile.workspace = true
tar.workspace = true
url.workspace = true
reqwest.workspace = true
same-file.workspace = true
cwl_engine_storage.workspace = true

# rdf
rdf.workspace = true
horned-owl.workspace = true

# util
chrono.workspace = true
anyhow.workspace = true
thiserror.workspace = true
miette.workspace = true
bon.workspace = true
tracing.workspace = true
async-trait.workspace = true
nonempty.workspace = true
sysinfo.workspace = true
semver.workspace = true
urlencoding.workspace = true
indexmap.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
regex.workspace = true
