[package]
name = "cwl_engine"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
serde.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
cwl_core.workspace = true
pathdiff = "0.2.3"
shlex = "1.3.0"
url = "2.5.8"