[package]
name = "cwl_core"
description = "Part of `CommonWL`. Document parsing"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bon.workspace = true
sha1.workspace = true
serde.workspace = true
serde_yaml.workspace = true
commonwl_salad = { version = "*", path = "../salad", features = ["derive"] }
url.workspace = true

[lib]
path = "lib.rs"
