[package]
name = "runner"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
crankshaft = { version = "0.8.0", features = ["docker"] }
commonwl = { path = "../crates/commonwl", features = ["execution"] }
serde_yaml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
tokio-util.workspace = true
clap = { version = "4.5.54", features = ["cargo"] }
